# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ac
import background
import image
from PyQt5.QtWidgets import QMessageBox

checklamp=0
checkac=0

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 601)
        MainWindow.setStyleSheet("background-image: url(:/background/background1.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 530, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_lamp = QtWidgets.QLabel(self.centralwidget)
        self.label_lamp.setGeometry(QtCore.QRect(650, 190, 131, 121))
        self.label_lamp.setStyleSheet("image: url(:/myimage/lamp_off.png);")
        self.label_lamp.setText("")
        self.label_lamp.setObjectName("label_lamp")
        self.btn_lamp_sleep = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lamp_sleep.setGeometry(QtCore.QRect(560, 380, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lamp_sleep.setFont(font)
        self.btn_lamp_sleep.setStyleSheet("background-image: url(:/background/blue1.png);")
        self.btn_lamp_sleep.setObjectName("btn_lamp_sleep")
        self.btn_lamp_on = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lamp_on.setGeometry(QtCore.QRect(670, 380, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lamp_on.setFont(font)
        self.btn_lamp_on.setStyleSheet("background-image: url(:/background/blue1.png);")
        self.btn_lamp_on.setObjectName("btn_lamp_on")
        self.btn_lamp_off = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lamp_off.setGeometry(QtCore.QRect(780, 380, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lamp_off.setFont(font)
        self.btn_lamp_off.setStyleSheet("background-image: url(:/background/blue1.png);")
        self.btn_lamp_off.setObjectName("btn_lamp_off")
        self.number_slider = QtWidgets.QSlider(self.centralwidget)
        self.number_slider.setGeometry(QtCore.QRect(200, 390, 271, 31))
        self.number_slider.setStyleSheet("")
        self.number_slider.setMinimum(16)
        self.number_slider.setMaximum(30)
        self.number_slider.setSingleStep(1)
        self.number_slider.setPageStep(1)
        self.number_slider.setSliderPosition(30)
        self.number_slider.setOrientation(QtCore.Qt.Horizontal)
        self.number_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.number_slider.setTickInterval(1)
        self.number_slider.setObjectName("number_slider")
        self.btn_on_ac = QtWidgets.QPushButton(self.centralwidget)
        self.btn_on_ac.setGeometry(QtCore.QRect(230, 440, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_on_ac.setFont(font)
        self.btn_on_ac.setStyleSheet("background-image: url(:/background/blue1.png);")
        self.btn_on_ac.setObjectName("btn_on_ac")
        self.btn_off_ac = QtWidgets.QPushButton(self.centralwidget)
        self.btn_off_ac.setGeometry(QtCore.QRect(350, 440, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_off_ac.setFont(font)
        self.btn_off_ac.setStyleSheet("background-image: url(:/background/blue1.png);")
        self.btn_off_ac.setObjectName("btn_off_ac")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(134, 190, 411, 191))
        self.label_3.setStyleSheet("image: url(:/myac/AC_off.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.display_number = QtWidgets.QLabel(self.centralwidget)
        self.display_number.setGeometry(QtCore.QRect(290, 230, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.display_number.setFont(font)
        self.display_number.setStyleSheet("background-image: url(:/background/white.png);")
        self.display_number.setAlignment(QtCore.Qt.AlignCenter)
        self.display_number.setObjectName("display_number")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 230, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-image: url(:/background/white.png);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 30, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_off_all = QtWidgets.QPushButton(self.centralwidget)
        self.btn_off_all.setGeometry(QtCore.QRect(10, 390, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_off_all.setFont(font)
        self.btn_off_all.setStyleSheet("background-image: url(:/background/blue1.png);")
        self.btn_off_all.setObjectName("btn_off_all")
        self.btn_on_all = QtWidgets.QPushButton(self.centralwidget)
        self.btn_on_all.setGeometry(QtCore.QRect(10, 330, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_on_all.setFont(font)
        self.btn_on_all.setStyleSheet("background-image: url(:/background/blue1.png);")
        self.btn_on_all.setObjectName("btn_on_all")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(780, 510, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("background-image: url(:/background/blue1.png);")
        self.btn_exit.setObjectName("btn_exit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 201, 151))
        self.label_2.setStyleSheet("image: url(:/background/logo.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        
        self.ac_off()
        self.btn_lamp_off.clicked.connect(self.lamp_off)
        self.btn_lamp_on.clicked.connect(self.lamp_on)
        self.btn_lamp_sleep.clicked.connect(self.lamp_sleep)

        self.number_slider.valueChanged.connect(self.new_value)

        self.btn_off_ac.clicked.connect(self.ac_off)
        self.btn_on_ac.clicked.connect(self.ac_on)

        self.btn_off_all.clicked.connect(self.all_off)
        self.btn_on_all.clicked.connect(self.all_on)

        self.btn_exit.clicked.connect(self.exit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nguyen Thuan Phat - MSSV: 21119349"))
        self.btn_lamp_sleep.setText(_translate("MainWindow", "SLEEP"))
        self.btn_lamp_on.setText(_translate("MainWindow", "ON"))
        self.btn_lamp_off.setText(_translate("MainWindow", "OFF"))
        self.btn_on_ac.setText(_translate("MainWindow", "ON"))
        self.btn_off_ac.setText(_translate("MainWindow", "OFF"))
        self.display_number.setText(_translate("MainWindow", ""))
        self.label_5.setText(_translate("MainWindow", "*C"))
        self.label_6.setText(_translate("MainWindow", "DIVICE CONTROL"))
        self.btn_off_all.setText(_translate("MainWindow", "OFF"))
        self.btn_on_all.setText(_translate("MainWindow", "ON"))
        self.label_7.setText(_translate("MainWindow", "Interrupt"))
        self.btn_exit.setText(_translate("MainWindow", "EXIT"))

    def lamp_off(self):
        self.label_lamp.setStyleSheet("image: url(:/myimage/lamp_off)")
    def lamp_on(self):
        self.label_lamp.setStyleSheet("image: url(:/myimage/lamp_on)")
    def lamp_sleep(self):
        self.label_lamp.setStyleSheet("image: url(:/myimage/lamp_on_sleep)")

    def new_value(self):
        self.display_number.setText(str(self.number_slider.value()))
        

       

    def ac_off(self):
        self.label_3.setStyleSheet("image: url(:/myac/AC_off)")
        self.number_slider.setEnabled(0)
        self.display_number.setText("")
    def ac_on(self):
        self.label_3.setStyleSheet("image: url(:/myac/AC_on)")  
        self.number_slider.setEnabled(1)
        self.new_value()

    def all_off(self):
        self.btn_lamp_off.setEnabled(0)
        self.btn_lamp_on.setEnabled(0)
        self.btn_lamp_sleep.setEnabled(0)
        self.btn_off_ac.setEnabled(0)
        self.btn_on_ac.setEnabled(0)
        global checklamp
        global checkac
        if self.label_lamp.styleSheet()=="image: url(:/myimage/lamp_on_sleep)":
            checklamp=1
        if self.label_lamp.styleSheet()=="image: url(:/myimage/lamp_on)":
            checklamp=2
        if self.label_3.styleSheet()=="image: url(:/myac/AC_on)":
            checkac=1

        self.lamp_off()
        self.ac_off()

    def all_on(self):
    
        self.btn_lamp_off.setEnabled(1)
        self.btn_lamp_on.setEnabled(1)
        self.btn_lamp_sleep.setEnabled(1)
        self.btn_off_ac.setEnabled(1)
        self.btn_on_ac.setEnabled(1)
        global checklamp
        global checkac
        if checklamp==1:
            self.lamp_sleep()
        if checklamp==2:
            self.lamp_on()
        if checkac==1:
            self.ac_on()
        checklamp=0
        checkac=0
       
    

    def exit(self):
        repmess=QMessageBox.question(MainWindow,'Confirm', 'Do you want to exit?', QMessageBox.Yes|QMessageBox.No)
        if repmess==QMessageBox.Yes:
            app.exit()
      
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
